### ISSUE TITLE
I don't have limited access to Azure Open AI

### ISSUE THREAD

**Issue by artemcodit** [microsoft/hack-together-dotnet#26]
![Screenshot 2023-11-22 132519](https://github.com/microsoft/hack-together-dotnet/assets/135232081/caeffc55-640d-4d10-837a-f4c70d650660)
Hello. Help me get access to get OpenAI, as I want to use this service in the project. 
I received two keys in the mail, but both don't work.

**Comment by justinyoo** [comment]
Hey, @artemcodit

You might have received a GUID as the access code. You need to use this access code with your GitHub alias like `your-access-code/github-alias`.

Please double check this document to get your access code working:

👉 https://github.com/microsoft/hack-together-dotnet/blob/main/OPENAI-README.md#instantiate-the-client

**Comment by justinyoo** [comment]
Oh, you mean the Playground page doesn't work as expected? Would you please provide us with the repro so that we can find out on our end?

**Comment by artemcodit** [comment]
Yes, playground doesn't work for me. In any case, the key also works well in my code. So you can close this topic. Thank you for your help!
