### ISSUE TITLE
Account create error

### ISSUE THREAD

**Issue by Sidzeppelin95** [microsoft/hack-together-dotnet#38]
I am trying to access the open ai after creating the resource group and subscription resource for open ai api but an error occurs in the subscription area where it does not recognize the subscription provided. When I looked at the documentation, it does not show the command to enter the subscription but in the training for openai the command is different. Please suggest!
![image](https://github.com/microsoft/hack-together-dotnet/assets/50958322/bafa5166-e03e-4b93-9b48-edecd4125fed)

**Comment by codemillmatt** [comment]
Hi @Sidzeppelin95 - are you using the proxy we're providing? If so, then you don't have to create an AOAI resource.

But if you do want your own AOAI resource - in that command, you can skip the `--subscription` option altogether and it'll use your default subscription to create the resource on.

Or - put single quotes around the subscription name.

Or, you could enter `az account list` and you'll then see a bunch of subscriptions that you have access to. Assuming you have permissions to create resources on the subscription you want to use - you can swap to it by using `az account set -s <NAME OR ID OR SUBSCRIPTION`

Probably more info than you were after, but I hope it helps.
